//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_tGjOsQutEe-pxaG5F_iUiQActivity"]="./../../plug-in_requerimientos/capabilitypatterns/resources/Analizar el problema_677AC8FB_677ac8fb_Activity.jpeg"
contentPage.processPage.imageFiles["_wYq00QuvEe-pxaG5F_iUiQActivity"]="./../../plug-in_requerimientos/capabilitypatterns/resources/Entendiendo las necesidades de los stakeholders_8D20E889_8d20e889_Activity.jpeg"
contentPage.processPage.imageFiles["_c70YkQvFEe-pxaG5F_iUiQActivity"]="./../../plug-in_requerimientos/capabilitypatterns/resources/Gestionar requerimientos cambiantes_D49D0199_d49d0199_Activity.jpeg"
contentPage.processPage.imageFiles["_f_QUYQvFEe-pxaG5F_iUiQActivity"]="./../../plug-in_requerimientos/capabilitypatterns/resources/Definición del sistema_3305C2AB_3305c2ab_Activity.jpeg"
contentPage.processPage.imageFiles["_lbabEQvFEe-pxaG5F_iUiQActivity"]="./../../plug-in_requerimientos/capabilitypatterns/resources/Gestionar el alcance del sistema_1051B539_1051b539_Activity.jpeg"
contentPage.processPage.imageFiles["_po8ygQvFEe-pxaG5F_iUiQActivity"]="./../../plug-in_requerimientos/capabilitypatterns/resources/Refinar la definición del sistema_4AF09280_4af09280_Activity.jpeg"
contentPage.processPage.imageFiles["_NdBU0QuwEe-pxaG5F_iUiQ,_vwfUUQvMEe-pxaG5F_iUiQActivity"]="./../../plug-in_requerimientos/deliveryprocesses/resources/Refinar la definición del sistema_2CB765C9_408f5f6f_Activity.jpeg"
contentPage.processPage.imageFiles["_NdBU0QuwEe-pxaG5F_iUiQ,_qFdrMAvMEe-pxaG5F_iUiQActivity"]="./../../plug-in_requerimientos/deliveryprocesses/resources/Gestionar requerimientos cambiantes_70B03814_848831ba_Activity.jpeg"
contentPage.processPage.imageFiles["_NdBU0QuwEe-pxaG5F_iUiQ,_uQEDYQvMEe-pxaG5F_iUiQActivity"]="./../../plug-in_requerimientos/deliveryprocesses/resources/Gestionar el alcance del sistema_5597A270_696f9c16_Activity.jpeg"
contentPage.processPage.imageFiles["_NdBU0QuwEe-pxaG5F_iUiQ,_O-iK4QuwEe-pxaG5F_iUiQActivity"]="./../../plug-in_requerimientos/deliveryprocesses/resources/Analizar el problema_3DFE1CA5_51d6164b_Activity.jpeg"
contentPage.processPage.imageFiles["_NdBU0QuwEe-pxaG5F_iUiQ,_P3z8QQuwEe-pxaG5F_iUiQActivity"]="./../../plug-in_requerimientos/deliveryprocesses/resources/Entendiendo las necesidades de los stakeholders_72BA30C9_86922a6f_Activity.jpeg"
contentPage.processPage.imageFiles["_NdBU0QuwEe-pxaG5F_iUiQ,_shAgkAvMEe-pxaG5F_iUiQActivity"]="./../../plug-in_requerimientos/deliveryprocesses/resources/Definición del sistema_B1B245CE_c58a3f74_Activity.jpeg"
contentPage.processPage.imageFiles["_NdBU0QuwEe-pxaG5F_iUiQActivity"]="./../../plug-in_requerimientos/deliveryprocesses/resources/Requerimientos_190DC152_190dc152_Activity.jpeg"
contentPage.processPage.elementUrls["_Z1jHAQvMEe-pxaG5F_iUiQ"] = ["Actor","plug-in_requerimientos/workproducts/actor_D6ED858C.html"];
contentPage.processPage.elementUrls["_FNP1AgvGEe-pxaG5F_iUiQ"] = ["Casos de uso","plug-in_requerimientos/workproducts/casos_de_uso_3CB4F1F3.html"];
contentPage.processPage.elementUrls["_WUUDqAvGEe-pxaG5F_iUiQ"] = ["Modelo de caso de uso empresarial","plug-in_requerimientos/workproducts/modelo_de_caso_de_uso_empresarial_6C8534FA.html"];
contentPage.processPage.elementUrls["_vwfUUQvMEe-pxaG5F_iUiQ"] = ["Refinar la definición del sistema","plug-in_requerimientos/deliveryprocesses/Refinar la definición del sistema_2CB765C9.html"];
contentPage.processPage.elementUrls["_p6YrUwvGEe-pxaG5F_iUiQ"] = ["Glosario","plug-in_requerimientos/workproducts/glosario_12E62413.html"];
contentPage.processPage.elementUrls["_tGjOsQutEe-pxaG5F_iUiQ"] = ["Analizar el problema","plug-in_requerimientos/capabilitypatterns/Analizar el problema_677AC8FB.html"];
contentPage.processPage.elementUrls["_lbabEQvFEe-pxaG5F_iUiQ"] = ["Gestionar el alcance del sistema","plug-in_requerimientos/capabilitypatterns/Gestionar el alcance del sistema_1051B539.html"];
contentPage.processPage.elementUrls["_ZtMD9QvGEe-pxaG5F_iUiQ"] = ["Lista de riesgos","plug-in_requerimientos/workproducts/lista_de_riesgos_C62FB3A0.html"];
contentPage.processPage.elementUrls["_WUUDpgvGEe-pxaG5F_iUiQ"] = ["Casos de negocio","plug-in_requerimientos/workproducts/casos_de_negocio_AFA357A5.html"];
contentPage.processPage.elementUrls["_P3z8QQuwEe-pxaG5F_iUiQ"] = ["Entendiendo las necesidades de los stakeholders","plug-in_requerimientos/deliveryprocesses/Entendiendo las necesidades de los stakeholders_72BA30C9.html"];
contentPage.processPage.elementUrls["_p6YrXwvGEe-pxaG5F_iUiQ"] = ["Casos de uso","plug-in_requerimientos/workproducts/casos_de_uso_3CB4F1F3.html"];
contentPage.processPage.elementUrls["_NdBU0QuwEe-pxaG5F_iUiQ"] = ["Requerimientos","plug-in_requerimientos/deliveryprocesses/Requerimientos_190DC152.html"];
contentPage.processPage.elementUrls["_YLzJsAvGEe-pxaG5F_iUiQ"] = ["Encontrar actores y casos de uso","plug-in_requerimientos/tasks/encontrar_actores_y_casos_de_uso_578EBAF5.html"];
contentPage.processPage.elementUrls["_g6yTEgvGEe-pxaG5F_iUiQ"] = ["Modelo de casos de uso","plug-in_requerimientos/workproducts/modelo_de_casos_de_uso_2C4F05A9.html"];
contentPage.processPage.elementUrls["_shAgkAvMEe-pxaG5F_iUiQ"] = ["Definición del sistema","plug-in_requerimientos/deliveryprocesses/Definición del sistema_B1B245CE.html"];
contentPage.processPage.elementUrls["_p6YrWwvGEe-pxaG5F_iUiQ"] = ["Visión","plug-in_requerimientos/workproducts/vision_EB734BD9.html"];
contentPage.processPage.elementUrls["_FNQcEgvGEe-pxaG5F_iUiQ"] = ["Paquete de casos de uso","plug-in_requerimientos/workproducts/paquete_de_casos_de_uso_C2EFB97E.html"];
contentPage.processPage.elementUrls["_MWRtMwvGEe-pxaG5F_iUiQ"] = ["Plan de gestión de requerimientos","plug-in_requerimientos/workproducts/plan_de_gestion_de_requerimientos_1E2B7FE5.html"];
contentPage.processPage.elementUrls["_hooQggvGEe-pxaG5F_iUiQ"] = ["Modelo de diseño","plug-in_requerimientos/workproducts/modelo_de_diseno_6A7D7D54.html"];
contentPage.processPage.elementUrls["_qxujAAvGEe-pxaG5F_iUiQ"] = ["Detallar requerimientos de software","plug-in_requerimientos/tasks/detallar_requerimientos_de_software_52333587.html"];
contentPage.processPage.elementUrls["_hol0SQvGEe-pxaG5F_iUiQ"] = ["Especificaciones suplementarias","plug-in_requerimientos/workproducts/especificaciones_suplementarias_E3690448.html"];
contentPage.processPage.elementUrls["_c70YkQvFEe-pxaG5F_iUiQ"] = ["Gestionar requerimientos cambiantes","plug-in_requerimientos/capabilitypatterns/Gestionar requerimientos cambiantes_D49D0199.html"];
contentPage.processPage.elementUrls["_WUUDrgvGEe-pxaG5F_iUiQ"] = ["Solicitudes de los Stakeholders","plug-in_requerimientos/workproducts/solicitudes_de_los_stakeholders_C44C7240.html"];
contentPage.processPage.elementUrls["_55ylwAuvEe-pxaG5F_iUiQ"] = ["Elicitar requerimientos de los stakeholders","plug-in_requerimientos/tasks/elicitar_requerimientos_de_los_stakeholders_BAE8F671.html"];
contentPage.processPage.elementUrls["_rqFuYAvGEe-pxaG5F_iUiQ"] = ["Modelar interfaz de usuario","plug-in_requerimientos/tasks/modelar_interfaz_de_usuario_9E40C15D.html"];
contentPage.processPage.elementUrls["_2vudgguvEe-pxaG5F_iUiQ"] = ["Visión","plug-in_requerimientos/workproducts/vision_EB734BD9.html"];
contentPage.processPage.elementUrls["_2vsBQAuvEe-pxaG5F_iUiQ"] = ["Capturar un vocabulario común","plug-in_requerimientos/tasks/capturar_un_vocabulario_comun_D116FCF5.html"];
contentPage.processPage.elementUrls["_MWRtNwvGEe-pxaG5F_iUiQ"] = ["Lista de riesgos","plug-in_requerimientos/workproducts/lista_de_riesgos_C62FB3A0.html"];
contentPage.processPage.elementUrls["_MWRtNQvGEe-pxaG5F_iUiQ"] = ["Solicitudes de los Stakeholders","plug-in_requerimientos/workproducts/solicitudes_de_los_stakeholders_C44C7240.html"];
contentPage.processPage.elementUrls["_GxFmVwvGEe-pxaG5F_iUiQ"] = ["Plan de iteración","plug-in_requerimientos/workproducts/plan_de_iteracion_7B729318.html"];
contentPage.processPage.elementUrls["_2vudiAuvEe-pxaG5F_iUiQ"] = ["Modelo de caso de uso empresarial","plug-in_requerimientos/workproducts/modelo_de_caso_de_uso_empresarial_6C8534FA.html"];
contentPage.processPage.elementUrls["_GxHbggvGEe-pxaG5F_iUiQ"] = ["Especificación de requerimientos de software","plug-in_requerimientos/workproducts/especificacion_de_requerimientos_de_software_26243B91.html"];
contentPage.processPage.elementUrls["_7YY8oAutEe-pxaG5F_iUiQ"] = ["Desarrollar visión","plug-in_requerimientos/tasks/desarrollar_la_vision_8326F0B0.html"];
contentPage.processPage.elementUrls["_z-eIyAutEe-pxaG5F_iUiQ"] = ["Solicitudes de los Stakeholders","plug-in_requerimientos/workproducts/solicitudes_de_los_stakeholders_C44C7240.html"];
contentPage.processPage.elementUrls["_iUPZUQvGEe-pxaG5F_iUiQ"] = ["Modelo de caso de uso empresarial","plug-in_requerimientos/workproducts/modelo_de_caso_de_uso_empresarial_6C8534FA.html"];
contentPage.processPage.elementUrls["_qFdrMAvMEe-pxaG5F_iUiQ"] = ["Gestionar requerimientos cambiantes","plug-in_requerimientos/deliveryprocesses/Gestionar requerimientos cambiantes_70B03814.html"];
contentPage.processPage.elementUrls["_41BWEguvEe-pxaG5F_iUiQ"] = ["Solicitud de cambio","plug-in_requerimientos/workproducts/solicitud_de_cambio_B198D63C.html"];
contentPage.processPage.elementUrls["_XXYqMwvGEe-pxaG5F_iUiQ"] = ["Especificaciones suplementarias","plug-in_requerimientos/workproducts/especificaciones_suplementarias_E3690448.html"];
contentPage.processPage.elementUrls["_g6xE8AvGEe-pxaG5F_iUiQ"] = ["Priorizar casos de uso","plug-in_requerimientos/tasks/priorizar_casos_de_uso_F82462FC.html"];
contentPage.processPage.elementUrls["_z-bshQutEe-pxaG5F_iUiQ"] = ["Modelo de casos de uso","plug-in_requerimientos/workproducts/modelo_de_casos_de_uso_2C4F05A9.html"];
contentPage.processPage.elementUrls["_z-eIwAutEe-pxaG5F_iUiQ"] = ["Casos de negocio","plug-in_requerimientos/workproducts/casos_de_negocio_AFA357A5.html"];
contentPage.processPage.elementUrls["_YLzJsQvGEe-pxaG5F_iUiQ"] = ["Directrices de modelado de casos de uso","plug-in_requerimientos/workproducts/directrices_de_modelado_de_casos_de_uso_89D02C89.html"];
contentPage.processPage.elementUrls["_qxw_QAvGEe-pxaG5F_iUiQ"] = ["Prototipo de interfaz de usuario","plug-in_requerimientos/workproducts/prototipo_de_interfaz_de_usuario_EB65CADF.html"];
contentPage.processPage.elementUrls["_g6yTFAvGEe-pxaG5F_iUiQ"] = ["Visión","plug-in_requerimientos/workproducts/vision_EB734BD9.html"];
contentPage.processPage.elementUrls["_6BDWQQutEe-pxaG5F_iUiQ"] = ["Plan de gestión de requerimientos","plug-in_requerimientos/workproducts/plan_de_gestion_de_requerimientos_1E2B7FE5.html"];
contentPage.processPage.elementUrls["_WUUDpAvGEe-pxaG5F_iUiQ"] = ["Modelo de casos de uso","plug-in_requerimientos/workproducts/modelo_de_casos_de_uso_2C4F05A9.html"];
contentPage.processPage.elementUrls["_FNOm4wvGEe-pxaG5F_iUiQ"] = ["Glosario","plug-in_requerimientos/workproducts/glosario_12E62413.html"];
contentPage.processPage.elementUrls["_40_g4AuvEe-pxaG5F_iUiQ"] = ["Administrar dependencias","plug-in_requerimientos/tasks/administrar_dependencias_1E053D79.html"];
contentPage.processPage.elementUrls["_FNQcEAvGEe-pxaG5F_iUiQ"] = ["Especificaciones suplementarias","plug-in_requerimientos/workproducts/especificaciones_suplementarias_E3690448.html"];
contentPage.processPage.elementUrls["_z-bsgAutEe-pxaG5F_iUiQ"] = ["Capturar un vocabulario común","plug-in_requerimientos/tasks/capturar_un_vocabulario_comun_D116FCF5.html"];
contentPage.processPage.elementUrls["_2vudkguvEe-pxaG5F_iUiQ"] = ["Glosario","plug-in_requerimientos/workproducts/glosario_12E62413.html"];
contentPage.processPage.elementUrls["_hol0QQvGEe-pxaG5F_iUiQ"] = ["Analista del sistema","plug-in_requerimientos/roles/analista_del_sistema_CF3A9E32.html"];
contentPage.processPage.elementUrls["_2vudjAuvEe-pxaG5F_iUiQ"] = ["Reglas del negocio","plug-in_requerimientos/workproducts/reglas_del_negocio_ECE171F3.html"];
contentPage.processPage.elementUrls["_7v8PEAuvEe-pxaG5F_iUiQ"] = ["Encontrar actores y casos de uso","plug-in_requerimientos/tasks/encontrar_actores_y_casos_de_uso_578EBAF5.html"];
contentPage.processPage.elementUrls["_hol0RQvGEe-pxaG5F_iUiQ"] = ["Solicitudes de los Stakeholders","plug-in_requerimientos/workproducts/solicitudes_de_los_stakeholders_C44C7240.html"];
contentPage.processPage.elementUrls["_p6YrUAvGEe-pxaG5F_iUiQ"] = ["Detallar un caso de uso","plug-in_requerimientos/tasks/detallar_un_caso_de_uso_696E9AAD.html"];
contentPage.processPage.elementUrls["_p6YrWQvGEe-pxaG5F_iUiQ"] = ["Solicitudes de los Stakeholders","plug-in_requerimientos/workproducts/solicitudes_de_los_stakeholders_C44C7240.html"];
contentPage.processPage.elementUrls["_z-eIxAutEe-pxaG5F_iUiQ"] = ["Modelo de objetos de negocio","plug-in_requerimientos/workproducts/modelo_de_objetos_de_negocio_2AF4EC38.html"];
contentPage.processPage.elementUrls["_2vudjguvEe-pxaG5F_iUiQ"] = ["Solicitudes de los Stakeholders","plug-in_requerimientos/workproducts/solicitudes_de_los_stakeholders_C44C7240.html"];
contentPage.processPage.elementUrls["_GxFmUQvGEe-pxaG5F_iUiQ"] = ["Revisor de requerimientos","plug-in_requerimientos/roles/revisor_de_requerimientos_2F1040EC.html"];
contentPage.processPage.elementUrls["_WUUDoAvGEe-pxaG5F_iUiQ"] = ["Analista del sistema","plug-in_requerimientos/roles/analista_del_sistema_CF3A9E32.html"];
contentPage.processPage.elementUrls["_PYzSIQwKEe-pxaG5F_iUiQ"] = ["Actor","plug-in_requerimientos/workproducts/actor_D6ED858C.html"];
contentPage.processPage.elementUrls["_ZtMD8wvGEe-pxaG5F_iUiQ"] = ["Solicitud de cambio","plug-in_requerimientos/workproducts/solicitud_de_cambio_B198D63C.html"];
contentPage.processPage.elementUrls["_6BDWQAutEe-pxaG5F_iUiQ"] = ["Desarrollar un plan de gestión de requerimientos","plug-in_requerimientos/tasks/desarrollar_un_plan_de_gestion_de_requerimeintos_B22BA127.html"];
contentPage.processPage.elementUrls["_g6yTEAvGEe-pxaG5F_iUiQ"] = ["Atributos de requerimientos","plug-in_requerimientos/workproducts/atributos_de_requerimientos_7228E778.html"];
contentPage.processPage.elementUrls["_3wdhwAuvEe-pxaG5F_iUiQ"] = ["Desarrollar visión","plug-in_requerimientos/tasks/desarrollar_la_vision_8326F0B0.html"];
contentPage.processPage.elementUrls["_41BWEAuvEe-pxaG5F_iUiQ"] = ["Plan de gestión de requerimientos","plug-in_requerimientos/workproducts/plan_de_gestion_de_requerimientos_1E2B7FE5.html"];
contentPage.processPage.elementUrls["_65-iUwutEe-pxaG5F_iUiQ"] = ["Especificaciones suplementarias","plug-in_requerimientos/workproducts/especificaciones_suplementarias_E3690448.html"];
contentPage.processPage.elementUrls["_GxFmUAvGEe-pxaG5F_iUiQ"] = ["Revisión de requerimientos","plug-in_requerimientos/tasks/revision_de_requerimientos_A5940A73.html"];
contentPage.processPage.elementUrls["_WUS1gAvGEe-pxaG5F_iUiQ"] = ["Capturar un vocabulario común","plug-in_requerimientos/tasks/capturar_un_vocabulario_comun_D116FCF5.html"];
contentPage.processPage.elementUrls["_z-eIxgutEe-pxaG5F_iUiQ"] = ["Reglas del negocio","plug-in_requerimientos/workproducts/reglas_del_negocio_ECE171F3.html"];
contentPage.processPage.elementUrls["_MWRtOQvGEe-pxaG5F_iUiQ"] = ["Modelo de diseño","plug-in_requerimientos/workproducts/modelo_de_diseno_6A7D7D54.html"];
contentPage.processPage.elementUrls["_PYRGoQwKEe-pxaG5F_iUiQ"] = ["Actor","plug-in_requerimientos/workproducts/actor_D6ED858C.html"];
contentPage.processPage.elementUrls["_p6YrYQvGEe-pxaG5F_iUiQ"] = ["Especificaciones suplementarias","plug-in_requerimientos/workproducts/especificaciones_suplementarias_E3690448.html"];
contentPage.processPage.elementUrls["_qxw_QgvGEe-pxaG5F_iUiQ"] = ["Especificación de requerimientos de software","plug-in_requerimientos/workproducts/especificacion_de_requerimientos_de_software_26243B91.html"];
contentPage.processPage.elementUrls["_rqFuYQvGEe-pxaG5F_iUiQ"] = ["Diseñador interfaz de usuarios","plug-in_requerimientos/roles/disenador_interfaz_de_usuarios_8230844.html"];
contentPage.processPage.elementUrls["_p6YrYwvGEe-pxaG5F_iUiQ"] = ["Atributos de requerimientos","plug-in_requerimientos/workproducts/atributos_de_requerimientos_7228E778.html"];
contentPage.processPage.elementUrls["_2vudkAuvEe-pxaG5F_iUiQ"] = ["Casos de uso","plug-in_requerimientos/workproducts/casos_de_uso_3CB4F1F3.html"];
contentPage.processPage.elementUrls["_GxFmVQvGEe-pxaG5F_iUiQ"] = ["Solicitud de cambio","plug-in_requerimientos/workproducts/solicitud_de_cambio_B198D63C.html"];
contentPage.processPage.elementUrls["_z-eIzAutEe-pxaG5F_iUiQ"] = ["Glosario","plug-in_requerimientos/workproducts/glosario_12E62413.html"];
contentPage.processPage.elementUrls["_FNOm4AvGEe-pxaG5F_iUiQ"] = ["Estructurar modelo de casos de uso","plug-in_requerimientos/tasks/estructurar_modelo_de_casos_de_uso_2340E10B.html"];
contentPage.processPage.elementUrls["_iUPZVQvGEe-pxaG5F_iUiQ"] = ["Reglas del negocio","plug-in_requerimientos/workproducts/reglas_del_negocio_ECE171F3.html"];
contentPage.processPage.elementUrls["_GxHbgAvGEe-pxaG5F_iUiQ"] = ["Prototipo de interfaz de usuario","plug-in_requerimientos/workproducts/prototipo_de_interfaz_de_usuario_EB65CADF.html"];
contentPage.processPage.elementUrls["_g6yTGAvGEe-pxaG5F_iUiQ"] = ["Documento de la arquitectura de software","plug-in_requerimientos/workproducts/documento_de_la_arquitectura_de_software_DD005621.html"];
contentPage.processPage.elementUrls["_iUPZUwvGEe-pxaG5F_iUiQ"] = ["Modelo de objetos de negocio","plug-in_requerimientos/workproducts/modelo_de_objetos_de_negocio_2AF4EC38.html"];
contentPage.processPage.elementUrls["_rqIxsAvGEe-pxaG5F_iUiQ"] = ["Directrices de interfaz de usuario","plug-in_requerimientos/workproducts/directrices_de_interfaz_de_usuario_50477902.html"];
contentPage.processPage.elementUrls["_z-bsgwutEe-pxaG5F_iUiQ"] = ["Visión","plug-in_requerimientos/workproducts/vision_EB734BD9.html"];
contentPage.processPage.elementUrls["_wYq00QuvEe-pxaG5F_iUiQ"] = ["Entendiendo las necesidades de los stakeholders","plug-in_requerimientos/capabilitypatterns/Entendiendo las necesidades de los stakeholders_8D20E889.html"];
contentPage.processPage.elementUrls["_2vudiguvEe-pxaG5F_iUiQ"] = ["Modelo de objetos de negocio","plug-in_requerimientos/workproducts/modelo_de_objetos_de_negocio_2AF4EC38.html"];
contentPage.processPage.elementUrls["_7v82IAuvEe-pxaG5F_iUiQ"] = ["Directrices de modelado de casos de uso","plug-in_requerimientos/workproducts/directrices_de_modelado_de_casos_de_uso_89D02C89.html"];
contentPage.processPage.elementUrls["_p6YrUQvGEe-pxaG5F_iUiQ"] = ["Especificador de requerimientos","plug-in_requerimientos/roles/especificador_de_requerimientos_CBBA9292.html"];
contentPage.processPage.elementUrls["_p6YrVwvGEe-pxaG5F_iUiQ"] = ["Plan de gestión de requerimientos","plug-in_requerimientos/workproducts/plan_de_gestion_de_requerimientos_1E2B7FE5.html"];
contentPage.processPage.elementUrls["_seVOwAvGEe-pxaG5F_iUiQ"] = ["Prototipo interfaz de usuario","plug-in_requerimientos/tasks/prototipo_interfaz_de_usuario_44A5FC09.html"];
contentPage.processPage.elementUrls["_WUUDsgvGEe-pxaG5F_iUiQ"] = ["Glosario","plug-in_requerimientos/workproducts/glosario_12E62413.html"];
contentPage.processPage.elementUrls["_p6YrVQvGEe-pxaG5F_iUiQ"] = ["Modelo de casos de uso","plug-in_requerimientos/workproducts/modelo_de_casos_de_uso_2C4F05A9.html"];
contentPage.processPage.elementUrls["_PZJQYQwKEe-pxaG5F_iUiQ"] = ["Actor","plug-in_requerimientos/workproducts/actor_D6ED858C.html"];
contentPage.processPage.elementUrls["_WUUDrAvGEe-pxaG5F_iUiQ"] = ["Reglas del negocio","plug-in_requerimientos/workproducts/reglas_del_negocio_ECE171F3.html"];
contentPage.processPage.elementUrls["_WUUDqgvGEe-pxaG5F_iUiQ"] = ["Modelo de objetos de negocio","plug-in_requerimientos/workproducts/modelo_de_objetos_de_negocio_2AF4EC38.html"];
contentPage.processPage.elementUrls["_FNOm5QvGEe-pxaG5F_iUiQ"] = ["Modelo de casos de uso","plug-in_requerimientos/workproducts/modelo_de_casos_de_uso_2C4F05A9.html"];
contentPage.processPage.elementUrls["_ZtMD8AvGEe-pxaG5F_iUiQ"] = ["Administrar dependencias","plug-in_requerimientos/tasks/administrar_dependencias_1E053D79.html"];
contentPage.processPage.elementUrls["_hol0RwvGEe-pxaG5F_iUiQ"] = ["Solicitud de cambio","plug-in_requerimientos/workproducts/solicitud_de_cambio_B198D63C.html"];
contentPage.processPage.elementUrls["_XXYqMQvGEe-pxaG5F_iUiQ"] = ["Atributos de requerimientos","plug-in_requerimientos/workproducts/atributos_de_requerimientos_7228E778.html"];
contentPage.processPage.elementUrls["_ZtMD8QvGEe-pxaG5F_iUiQ"] = ["Plan de gestión de requerimientos","plug-in_requerimientos/workproducts/plan_de_gestion_de_requerimientos_1E2B7FE5.html"];
contentPage.processPage.elementUrls["_O-iK4QuwEe-pxaG5F_iUiQ"] = ["Analizar el problema","plug-in_requerimientos/deliveryprocesses/Analizar el problema_3DFE1CA5.html"];
contentPage.processPage.elementUrls["_2vudhguvEe-pxaG5F_iUiQ"] = ["Casos de negocio","plug-in_requerimientos/workproducts/casos_de_negocio_AFA357A5.html"];
contentPage.processPage.elementUrls["_41B9IAuvEe-pxaG5F_iUiQ"] = ["Lista de riesgos","plug-in_requerimientos/workproducts/lista_de_riesgos_C62FB3A0.html"];
contentPage.processPage.elementUrls["_z-eIygutEe-pxaG5F_iUiQ"] = ["Casos de uso","plug-in_requerimientos/workproducts/casos_de_uso_3CB4F1F3.html"];
contentPage.processPage.elementUrls["_FNP1AAvGEe-pxaG5F_iUiQ"] = ["Directrices de modelado de casos de uso","plug-in_requerimientos/workproducts/directrices_de_modelado_de_casos_de_uso_89D02C89.html"];
contentPage.processPage.elementUrls["_GxFmUwvGEe-pxaG5F_iUiQ"] = ["Visión","plug-in_requerimientos/workproducts/vision_EB734BD9.html"];
contentPage.processPage.elementUrls["_XXYqMAvGEe-pxaG5F_iUiQ"] = ["Desarrollar visión","plug-in_requerimientos/tasks/desarrollar_la_vision_8326F0B0.html"];
contentPage.processPage.elementUrls["_3wdhwwuvEe-pxaG5F_iUiQ"] = ["Especificaciones suplementarias","plug-in_requerimientos/workproducts/especificaciones_suplementarias_E3690448.html"];
contentPage.processPage.elementUrls["_g6yTFgvGEe-pxaG5F_iUiQ"] = ["Plan de iteración","plug-in_requerimientos/workproducts/plan_de_iteracion_7B729318.html"];
contentPage.processPage.elementUrls["_hooQgAvGEe-pxaG5F_iUiQ"] = ["Lista de riesgos","plug-in_requerimientos/workproducts/lista_de_riesgos_C62FB3A0.html"];
contentPage.processPage.elementUrls["_rqJYwAvGEe-pxaG5F_iUiQ"] = ["Guión gráfico de casos de uso","plug-in_requerimientos/workproducts/guion_grafico_de_casos_de_uso_209C4B2B.html"];
contentPage.processPage.elementUrls["_f_QUYQvFEe-pxaG5F_iUiQ"] = ["Definición del sistema","plug-in_requerimientos/capabilitypatterns/Definición del sistema_3305C2AB.html"];
contentPage.processPage.elementUrls["_iUPZUAvGEe-pxaG5F_iUiQ"] = ["Desarrollar visión","plug-in_requerimientos/tasks/desarrollar_la_vision_8326F0B0.html"];
contentPage.processPage.elementUrls["_po8ygQvFEe-pxaG5F_iUiQ"] = ["Refinar la definición del sistema","plug-in_requerimientos/capabilitypatterns/Refinar la definición del sistema_4AF09280.html"];
contentPage.processPage.elementUrls["_2vudhAuvEe-pxaG5F_iUiQ"] = ["Modelo de casos de uso","plug-in_requerimientos/workproducts/modelo_de_casos_de_uso_2C4F05A9.html"];
contentPage.processPage.elementUrls["_41B9IguvEe-pxaG5F_iUiQ"] = ["Modelo de diseño","plug-in_requerimientos/workproducts/modelo_de_diseno_6A7D7D54.html"];
contentPage.processPage.elementUrls["_ZtMD9wvGEe-pxaG5F_iUiQ"] = ["Modelo de diseño","plug-in_requerimientos/workproducts/modelo_de_diseno_6A7D7D54.html"];
contentPage.processPage.elementUrls["_65-iUQutEe-pxaG5F_iUiQ"] = ["Directrices de modelado de casos de uso","plug-in_requerimientos/workproducts/directrices_de_modelado_de_casos_de_uso_89D02C89.html"];
contentPage.processPage.elementUrls["_65-iUAutEe-pxaG5F_iUiQ"] = ["Encontrar actores y casos de uso","plug-in_requerimientos/tasks/encontrar_actores_y_casos_de_uso_578EBAF5.html"];
contentPage.processPage.elementUrls["_3wdhwQuvEe-pxaG5F_iUiQ"] = ["Atributos de requerimientos","plug-in_requerimientos/workproducts/atributos_de_requerimientos_7228E778.html"];
contentPage.processPage.elementUrls["_WUUDogvGEe-pxaG5F_iUiQ"] = ["Visión","plug-in_requerimientos/workproducts/vision_EB734BD9.html"];
contentPage.processPage.elementUrls["_MWRtMQvGEe-pxaG5F_iUiQ"] = ["Atributos de requerimientos","plug-in_requerimientos/workproducts/atributos_de_requerimientos_7228E778.html"];
contentPage.processPage.elementUrls["_g6xE8QvGEe-pxaG5F_iUiQ"] = ["Arquitecto software","plug-in_requerimientos/roles/arquitecto_software_D7F7AD76.html"];
contentPage.processPage.elementUrls["_p6YrXQvGEe-pxaG5F_iUiQ"] = ["Directrices de modelado de casos de uso","plug-in_requerimientos/workproducts/directrices_de_modelado_de_casos_de_uso_89D02C89.html"];
contentPage.processPage.elementUrls["_FNOm4QvGEe-pxaG5F_iUiQ"] = ["Analista del sistema","plug-in_requerimientos/roles/analista_del_sistema_CF3A9E32.html"];
contentPage.processPage.elementUrls["_GxHbhAvGEe-pxaG5F_iUiQ"] = ["Revisar registro","plug-in_requerimientos/workproducts/revisar_registro_CBC0C8E8.html"];
contentPage.processPage.elementUrls["_z-bsgQutEe-pxaG5F_iUiQ"] = ["Analista del sistema","plug-in_requerimientos/roles/analista_del_sistema_CF3A9E32.html"];
contentPage.processPage.elementUrls["_MWRtMAvGEe-pxaG5F_iUiQ"] = ["Administrar dependencias","plug-in_requerimientos/tasks/administrar_dependencias_1E053D79.html"];
contentPage.processPage.elementUrls["_uQEDYQvMEe-pxaG5F_iUiQ"] = ["Gestionar el alcance del sistema","plug-in_requerimientos/deliveryprocesses/Gestionar el alcance del sistema_5597A270.html"];
contentPage.processPage.elementUrls["_z-eIwgutEe-pxaG5F_iUiQ"] = ["Modelo de caso de uso empresarial","plug-in_requerimientos/workproducts/modelo_de_caso_de_uso_empresarial_6C8534FA.html"];
contentPage.processPage.elementUrls["_Z1jHBAvMEe-pxaG5F_iUiQ"] = ["Clase limite","plug-in_requerimientos/workproducts/clase_límite_44AADF95.html"];
contentPage.processPage.elementUrls["_hol0QAvGEe-pxaG5F_iUiQ"] = ["Administrar dependencias","plug-in_requerimientos/tasks/administrar_dependencias_1E053D79.html"];
contentPage.processPage.elementUrls["_7YZjsAutEe-pxaG5F_iUiQ"] = ["Atributos de requerimientos","plug-in_requerimientos/workproducts/atributos_de_requerimientos_7228E778.html"];
contentPage.processPage.elementUrls["_WUUDsAvGEe-pxaG5F_iUiQ"] = ["Casos de uso","plug-in_requerimientos/workproducts/casos_de_uso_3CB4F1F3.html"];
contentPage.processPage.elementUrls["_hol0QwvGEe-pxaG5F_iUiQ"] = ["Plan de gestión de requerimientos","plug-in_requerimientos/workproducts/plan_de_gestion_de_requerimientos_1E2B7FE5.html"];
contentPage.processPage.elementUrls["_2vudgAuvEe-pxaG5F_iUiQ"] = ["Analista del sistema","plug-in_requerimientos/roles/analista_del_sistema_CF3A9E32.html"];
